<a href="https://colab.research.google.com/github/a-nastasiamoiseeva/python-ai-Moiseeva-Anastasia/blob/main/notebooks/week2b_read_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
# 🔹 Шаг 0. Все импорты в одном месте
import os
import pandas as pd
from IPython.display import display

📊 Week 2: Data Analysis — Чтение и проверка данных
Цель: Научиться читать CSV-файлы из репозитория GitHub в Google Colab и выполнять базовую проверку данных с помощью pandas.

**Данные:**

**books_authors.csv** — информация о книгах: ID книги, название, ID автора, имя автора, жанр, дата публикации, издательство
**authors.csv** — информация об авторах: ID автора, псевдонимы/имена, дата рождения, примечания

Что мы делаем:

* **Клонируем ваш персональный репозиторий** `python-ai-Moiseeva-Anastasia` в Colab
* Читаем CSV-файлы в pandas DataFrame
* Очищаем и переименовываем столбцы
* Смотрим структуру данных и делаем быструю валидацию

## 🐱 [1] Клонируем репозиторий курса в Colab

In [48]:
# 🐱 Шаг 1. Клонируем ваш репозиторий в Colab

# **УДАЛЕНО: import os (теперь в Шаге 0)**

# Имя репозитория под ваш проект
repo = "python-ai-Moiseeva-Anastasia"
repo_path = f"/content/{repo}"

if not os.path.exists(repo_path):
    # URL клонирования под ваш GitHub
    !git clone -q https://github.com/a-nastasiamoiseeva/python-ai-Moiseeva-Anastasia.git

if os.getcwd() != repo_path:
    %cd {repo_path}

print("✅ Репозиторий готов, теперь мы работаем внутри папки", repo)

✅ Репозиторий готов, теперь мы работаем внутри папки python-ai-Moiseeva-Anastasia

## 📥 [2A] Простое чтение CSV-файлов в pandas

Сначала просто прочитаем оба CSV-файла в объекты `DataFrame`, без каких‑либо изменений.

После этого мы узнаем, сколько строк загружено в каждый датасет.

In [49]:
# 🐱 Шаг 2A. Чтение CSV-файлов в pandas

# Читаем файлы с базовыми параметрами для надёжного парсинга
df_books = pd.read_csv(
    "data/books_authors.csv",
    sep=",",
    encoding="utf-8",
    skipinitialspace=True,      # убирает пробелы после запятых
    on_bad_lines="skip"         # пропускает строки с битой структурой
)

df_authors = pd.read_csv(
    "data/authors.csv",
    sep=",",
    encoding="utf-8",
    skipinitialspace=True,
    on_bad_lines="skip"
)

# Гарантируем чистые заголовки (убираем скрытые пробелы в именах столбцов)
df_books.columns = df_books.columns.str.strip()
df_authors.columns = df_authors.columns.str.strip()

# Базовая информация о размере данных
print("✅ Загружено строк в df_books:", len(df_books))
print("✅ Загружено строк в df_authors:", len(df_authors))

# 🔍 «Первый взгляд на коробку с деталями»: показываем сырые данные до любых преобразований
print("\n📋 df_books — первые 5 строк (исходные):")
display(df_books.head())

print("\n📋 df_authors — первые 5 строк (исходные):")
display(df_authors.head())

✅ Загружено строк в df_books: 4148
✅ Загружено строк в df_authors: 1650

📋 df_books — первые 5 строк (исходные):

,book,bookLabel,author,authorLabel,genreLabel,pubDate,publisherLabel
0,http://www.wikidata.org/entity/Q603705,...Яко помниши его,http://www.wikidata.org/entity/Q34981,Айзек Азимов,научная фантастика,1974-05-01T00:00:00Z,NaN
1,http://www.wikidata.org/entity/Q427110,Пересадочная станция,http://www.wikidata.org/entity/Q294625,Клиффорд Дональд Саймак,научная фантастика,1963-06-01T00:00:00Z,Doubleday
2,http://www.wikidata.org/entity/Q1114499,Пасынки Вселенной,http://www.wikidata.org/entity/Q123078,Роберт Хайнлайн,научная фантастика,1963-01-01T00:00:00Z,Victor Gollancz
3,http://www.wikidata.org/entity/Q617357,Убик,http://www.wikidata.org/entity/Q171091,Филип Дик,научная фантастика,1969-01-01T00:00:00Z,Doubleday
4,http://www.wikidata.org/entity/Q388200,The Bloody Sun,http://www.wikidata.org/entity/Q465179,Мэрион Зиммер Брэдли,научная фантастика,1964-01-01T00:00:00Z,Ace Books

📋 df_authors — первые 5 строк (исходные):

,author,pseudonymLabel,birthDate,spouseLabel
0,http://www.wikidata.org/entity/Q465179,Astra Zimmer,1930-06-03T00:00:00Z,Walter Breen
1,http://www.wikidata.org/entity/Q465179,Astra Zimmer Bradley,1930-06-03T00:00:00Z,Walter Breen
2,http://www.wikidata.org/entity/Q465179,John Jay Wells,1930-06-03T00:00:00Z,Walter Breen
3,http://www.wikidata.org/entity/Q1160619,Louis G. Daniels,1920-02-11T00:00:00Z,NaN
4,http://www.wikidata.org/entity/Q82032,NaN,1924-11-21T00:00:00Z,Faith Tully Lilly Faulconbridge

## 🧹 [2B] Очистка и переименование столбцов

В исходных CSV-файлах есть **технические столбцы с URL Wikidata** и столбцы с постфиксом `Label`, которые содержат читаемые названия.

В этом шаге мы **не удаляем URL из Wikidata**, а сохраняем их как отдельные столбцы `book_URL` и `author_URL`.

Это нужно по двум причинам:
- URL помогает открыть объект в Wikidata и вручную проверить странную запись;
- URL нужен для `merge()`, `drop_duplicates()` и точного подсчёта уникальных книг и авторов.

Столбцы вида `*Label` мы переименовываем в короткие читаемые имена:
- `bookLabel` → `book`
- `authorLabel` → `author_name`
- `genreLabel` → `genre`
- `publisherLabel` → `publisher`
- `pseudonymLabel` → `pseudonym`
- `spouseLabel` → `spouse`

Дополнительно мы преобразуем столбцы с датами (`pubDate`, `birthDate`) в формат `datetime`, чтобы в дальнейшем удобно извлекать годы и строить временные срезы.

> ⚠️ **Важно:** Код автоматически проверяет наличие столбцов, убирает возможные дубликаты имён после переименования и создаёт копию DataFrame (`.copy()`), чтобы избежать предупреждений `SettingWithCopyWarning` при дальнейшей работе.

In [50]:
# 🧹 Шаг 2B. Очистка и переименование столбцов

# ─────────────────────────────────────────────────────
# df_books: НЕ удаляем URL, а переименовываем с суффиксом _URL
# ─────────────────────────────────────────────────────
rename_books = {
    "book": "book_URL",              # **ИЗМЕНЕНО: сохраняем URL книги**
    "bookLabel": "book",             # читаемое название книги
    "author": "author_URL",          # **ИЗМЕНЕНО: сохраняем URL автора**
    "authorLabel": "author_name",    # **ИЗМЕНЕНО: имя автора (чтобы не путать с URL)**
    "genreLabel": "genre",
    "publisherLabel": "publisher"
}

df_books = df_books.rename(
    columns={k: v for k, v in rename_books.items() if k in df_books.columns}
)
# Убираем дубликаты имён и создаём копию (защита от SettingWithCopyWarning)
df_books = df_books.loc[:, ~df_books.columns.duplicated()].copy()

# ─────────────────────────────────────────────────────
# df_authors: тоже сохраняем URL автора
# ─────────────────────────────────────────────────────
rename_authors = {
    "author": "author_URL",          # **ИЗМЕНЕНО: сохраняем URL автора**
    "pseudonymLabel": "pseudonym",
    "spouseLabel": "spouse"
}

df_authors = df_authors.rename(
    columns={k: v for k, v in rename_authors.items() if k in df_authors.columns}
)
df_authors = df_authors.loc[:, ~df_authors.columns.duplicated()].copy()

# ─────────────────────────────────────────────────────
# Преобразуем даты в формат datetime для удобной работы
# ─────────────────────────────────────────────────────
if "pubDate" in df_books.columns:
    df_books["pubDate"] = pd.to_datetime(df_books["pubDate"], errors="coerce")

if "birthDate" in df_authors.columns:
    df_authors["birthDate"] = pd.to_datetime(df_authors["birthDate"], errors="coerce")

# 🔽 Вывод итоговых столбцов
print("Итоговые столбцы df_books:", list(df_books.columns))
print("Итоговые столбцы df_authors:", list(df_authors.columns))

Итоговые столбцы df_books: ['book_URL', 'book', 'author_URL', 'author_name', 'genre', 'pubDate', 'publisher']
Итоговые столбцы df_authors: ['author_URL', 'pseudonym', 'birthDate', 'spouse']

`df_books` находится в длинном формате: строк больше, чем уникальных книг.

Это означает, что одна и та же книга может встречаться в нескольких строках.
Для анализа связей это нормально, но для общей статистики по книгам нужно будет создать `df_books_unique`.

In [51]:
# Шаг 2C. Проверяем, есть ли длинный формат

print("Строк всего в df_books:", len(df_books))
print("Уникальных книг:", df_books["book_URL"].nunique())
print("Уникальных авторов:", df_books["author_URL"].nunique())

avg_rows_per_book = len(df_books) / df_books["book_URL"].nunique()
print("Среднее число строк на одну книгу:", round(avg_rows_per_book, 2))

Строк всего в df_books: 4148
Уникальных книг: 3365
Уникальных авторов: 731
Среднее число строк на одну книгу: 1.23

## 🔍 [3] Обзор данных: структура и первые строки

Сделаем короткий обзор обоих DataFrame с вашими данными:

### 📚 `df_books` (из books_authors.csv)
После очистки содержит столбцы:
- `book` — название книги
- `author` — имя автора
- `genre` — жанр произведения
- `pubDate` — дата публикации
- `publisher` — издательство

### 👤 `df_authors` (из authors.csv)
После очистки содержит столбцы:
- `pseudonym` — псевдоним или имя автора
- `birthDate` — дата рождения
- `spouse` — супруг/супруга (если указано)

### Что мы делаем:
- посмотрим размер таблицы (`shape`);
- выведем список столбцов;
- посмотрим первые несколько строк;
- **дополнительно проверим типы данных и наличие пропусков** (`info()` и `isna().sum()`).

Для удобства напишем маленькую функцию `show_info(df, name)`, чтобы не повторять один и тот же код два раза.

In [52]:
# Шаг 3. Создаём таблицу уникальных книг
df_books_unique = df_books.drop_duplicates(subset="book_URL").copy()

print("Строк в df_books:", len(df_books))
print("Строк в df_books_unique:", len(df_books_unique))
display(df_books_unique.head())

Строк в df_books: 4148
Строк в df_books_unique: 3365

,book_URL,book,author_URL,author_name,genre,pubDate,publisher
0,http://www.wikidata.org/entity/Q603705,...Яко помниши его,http://www.wikidata.org/entity/Q34981,Айзек Азимов,научная фантастика,1974-05-01 00:00:00+00:00,NaN
1,http://www.wikidata.org/entity/Q427110,Пересадочная станция,http://www.wikidata.org/entity/Q294625,Клиффорд Дональд Саймак,научная фантастика,1963-06-01 00:00:00+00:00,Doubleday
2,http://www.wikidata.org/entity/Q1114499,Пасынки Вселенной,http://www.wikidata.org/entity/Q123078,Роберт Хайнлайн,научная фантастика,1963-01-01 00:00:00+00:00,Victor Gollancz
3,http://www.wikidata.org/entity/Q617357,Убик,http://www.wikidata.org/entity/Q171091,Филип Дик,научная фантастика,1969-01-01 00:00:00+00:00,Doubleday
4,http://www.wikidata.org/entity/Q388200,The Bloody Sun,http://www.wikidata.org/entity/Q465179,Мэрион Зиммер Брэдли,научная фантастика,1964-01-01 00:00:00+00:00,Ace Books

In [53]:
def show_info(df, name, n=5):
    print(f"\n📊 {name}")
    print("Размер:", df.shape)
    print("Столбцы:", ", ".join(df.columns))
    print("\nТипы данных:")
    print(df.dtypes.to_string())
    print("\nПропущенные значения:")
    print(df.isna().sum())
    print(f"\nПервые {n} строк:")
    display(df.head(n))

show_info(df_books, "Связи книга–автор–жанр (df_books)")
show_info(df_books_unique, "Уникальные книги (df_books_unique)")
show_info(df_authors, "Авторы (df_authors)")

📊 Связи книга–автор–жанр (df_books)
Размер: (4148, 7)
Столбцы: book_URL, book, author_URL, author_name, genre, pubDate, publisher

Типы данных:
book_URL                    object
book                        object
author_URL                  object
author_name                 object
genre                       object
pubDate        datetime64[ns, UTC]
publisher                   object

Пропущенные значения:
book_URL          0
book              0
author_URL        0
author_name       0
genre             0
pubDate           0
publisher      2788
dtype: int64

Первые 5 строк:

,book_URL,book,author_URL,author_name,genre,pubDate,publisher
0,http://www.wikidata.org/entity/Q603705,...Яко помниши его,http://www.wikidata.org/entity/Q34981,Айзек Азимов,научная фантастика,1974-05-01 00:00:00+00:00,NaN
1,http://www.wikidata.org/entity/Q427110,Пересадочная станция,http://www.wikidata.org/entity/Q294625,Клиффорд Дональд Саймак,научная фантастика,1963-06-01 00:00:00+00:00,Doubleday
2,http://www.wikidata.org/entity/Q1114499,Пасынки Вселенной,http://www.wikidata.org/entity/Q123078,Роберт Хайнлайн,научная фантастика,1963-01-01 00:00:00+00:00,Victor Gollancz
3,http://www.wikidata.org/entity/Q617357,Убик,http://www.wikidata.org/entity/Q171091,Филип Дик,научная фантастика,1969-01-01 00:00:00+00:00,Doubleday
4,http://www.wikidata.org/entity/Q388200,The Bloody Sun,http://www.wikidata.org/entity/Q465179,Мэрион Зиммер Брэдли,научная фантастика,1964-01-01 00:00:00+00:00,Ace Books

📊 Уникальные книги (df_books_unique)
Размер: (3365, 7)
Столбцы: book_URL, book, author_URL, author_name, genre, pubDate, publisher

Типы данных:
book_URL                    object
book                        object
author_URL                  object
author_name                 object
genre                       object
pubDate        datetime64[ns, UTC]
publisher                   object

Пропущенные значения:
book_URL          0
book              0
author_URL        0
author_name       0
genre             0
pubDate           0
publisher      2271
dtype: int64

Первые 5 строк:

,book_URL,book,author_URL,author_name,genre,pubDate,publisher
0,http://www.wikidata.org/entity/Q603705,...Яко помниши его,http://www.wikidata.org/entity/Q34981,Айзек Азимов,научная фантастика,1974-05-01 00:00:00+00:00,NaN
1,http://www.wikidata.org/entity/Q427110,Пересадочная станция,http://www.wikidata.org/entity/Q294625,Клиффорд Дональд Саймак,научная фантастика,1963-06-01 00:00:00+00:00,Doubleday
2,http://www.wikidata.org/entity/Q1114499,Пасынки Вселенной,http://www.wikidata.org/entity/Q123078,Роберт Хайнлайн,научная фантастика,1963-01-01 00:00:00+00:00,Victor Gollancz
3,http://www.wikidata.org/entity/Q617357,Убик,http://www.wikidata.org/entity/Q171091,Филип Дик,научная фантастика,1969-01-01 00:00:00+00:00,Doubleday
4,http://www.wikidata.org/entity/Q388200,The Bloody Sun,http://www.wikidata.org/entity/Q465179,Мэрион Зиммер Брэдли,научная фантастика,1964-01-01 00:00:00+00:00,Ace Books

📊 Авторы (df_authors)
Размер: (1650, 4)
Столбцы: author_URL, pseudonym, birthDate, spouse

Типы данных:
author_URL                 object
pseudonym                  object
birthDate     datetime64[ns, UTC]
spouse                     object

Пропущенные значения:
author_URL       0
pseudonym      997
birthDate       62
spouse        1172
dtype: int64

Первые 5 строк:

,author_URL,pseudonym,birthDate,spouse
0,http://www.wikidata.org/entity/Q465179,Astra Zimmer,1930-06-03 00:00:00+00:00,Walter Breen
1,http://www.wikidata.org/entity/Q465179,Astra Zimmer Bradley,1930-06-03 00:00:00+00:00,Walter Breen
2,http://www.wikidata.org/entity/Q465179,John Jay Wells,1930-06-03 00:00:00+00:00,Walter Breen
3,http://www.wikidata.org/entity/Q1160619,Louis G. Daniels,1920-02-11 00:00:00+00:00,NaN
4,http://www.wikidata.org/entity/Q82032,NaN,1924-11-21 00:00:00+00:00,Faith Tully Lilly Faulconbridge

In [54]:
# Шаг 3B. Производные временные признаки

if "pubDate" in df_books.columns:
    df_books["pubYear"] = df_books["pubDate"].dt.year
    df_books["decade"] = (df_books["pubYear"] // 10) * 10

if "pubDate" in df_books_unique.columns:
    df_books_unique["pubYear"] = df_books_unique["pubDate"].dt.year
    df_books_unique["decade"] = (df_books_unique["pubYear"] // 10) * 10

if "birthDate" in df_authors.columns:
    df_authors["birthYear"] = df_authors["birthDate"].dt.year

display(df_books[["book", "pubDate", "pubYear", "decade"]].head())
display(df_authors[["author_URL", "birthDate", "birthYear"]].head())

                   book                   pubDate  pubYear  decade
0    ...Яко помниши его 1974-05-01 00:00:00+00:00     1974    1970
1  Пересадочная станция 1963-06-01 00:00:00+00:00     1963    1960
2     Пасынки Вселенной 1963-01-01 00:00:00+00:00     1963    1960
3                  Убик 1969-01-01 00:00:00+00:00     1969    1960
4        The Bloody Sun 1964-01-01 00:00:00+00:00     1964    1960

,author_URL,birthDate,birthYear
0,http://www.wikidata.org/entity/Q465179,1930-06-03 00:00:00+00:00,1930.0
1,http://www.wikidata.org/entity/Q465179,1930-06-03 00:00:00+00:00,1930.0
2,http://www.wikidata.org/entity/Q465179,1930-06-03 00:00:00+00:00,1930.0
3,http://www.wikidata.org/entity/Q1160619,1920-02-11 00:00:00+00:00,1920.0
4,http://www.wikidata.org/entity/Q82032,1924-11-21 00:00:00+00:00,1924.0

## 📈 [4] Быстрая проверка и валидация данных: ключевые метрики

В этом шаге мы проведём три базовых, но информативных анализа по датасету `df_books`:

### 1️⃣ Топ-5 самых публикуемых авторов
- Посчитаем, сколько книг принадлежит каждому автору.
- Выведем рейтинг в порядке убывания.
- *Вопрос:* Кто из авторов наиболее представлен в нашей выборке?

### 2️⃣ Топ-5 самых активных издательств
- Подсчитаем количество книг для каждого издательства.
- Определим лидеров по объёму публикаций.
- *Вопрос:* Какие издательства доминируют в жанре научной фантастики?

### 3️⃣ Публикационная активность по десятилетиям
- Сгруппируем книги по десятилетиям (1960-е, 1970-е, 1980-е и т.д.).
- Посчитаем количество книг в каждом периоде.
- *Вопрос:* В какие десятилетия наблюдался пик публикаций?

> 💡 **Технические моменты:**
> - Используем `value_counts()` для быстрого подсчёта уникальных значений.
> - Для работы с датами применяем `pd.to_datetime()` и извлекаем год через `.dt.year`.
> - Группировку по десятилетиям делаем через целочисленное деление: `год // 10 * 10`.
> - Все операции защищены проверками: если столбец отсутствует или пуст, код выведет понятное предупреждение, а не ошибку.

In [55]:
# Шаг 4A. Заполненность полей

coverage = pd.DataFrame({
    "field": ["publisher", "pseudonym", "birthDate", "spouse"],
    "non_null_share": [
        df_books["publisher"].notna().mean() if "publisher" in df_books.columns else None,
        df_authors["pseudonym"].notna().mean() if "pseudonym" in df_authors.columns else None,
        df_authors["birthDate"].notna().mean() if "birthDate" in df_authors.columns else None,
        df_authors["spouse"].notna().mean() if "spouse" in df_authors.columns else None,
    ]
})

coverage["percent"] = (coverage["non_null_share"] * 100).round(1)
display(coverage[["field", "percent"]])

       field  percent
0  publisher     32.8
1  pseudonym     39.6
2  birthDate     96.2
3     spouse     29.0

По этой таблице видно, какие поля подходят для графиков на всей выборке, а какие — только для подвыборки.

Если поле заполнено редко, это не значит, что оно бесполезно.
Это значит, что график по нему надо строить аккуратно и обязательно подписывать размер выборки.

## 🔗 [4B-4C] Объединение книг и авторов по URL

В исходных данных один автор может встречаться в нескольких строках `df_authors` (разные псевдонимы, супруги и т.д.).
Прямой `merge` по имени может создать дубли или потерять связи из-за разного написания.

Поэтому мы:
1. **Агрегируем** `df_authors` до одной строки на каждый `author_URL`.
2. Собираем псевдонимы и супругов в аккуратные списки без повторов.
3. Делаем **безопасный merge** `df_books_unique` с агрегированными авторами по `author_URL` с проверкой `validate="m:1"`.

In [56]:
# Шаг 4B. Агрегируем авторов до одной строки на author_URL

def unique_list(series):
    return sorted(set(series.dropna()))

df_authors_agg = (
    df_authors.groupby("author_URL", dropna=False)
    .agg(
        birthDate=("birthDate", "first"),
        birthYear=("birthYear", "first"),
        pseudonyms=("pseudonym", unique_list),
        spouses=("spouse", unique_list)
    )
    .reset_index()
)

print("Строк в исходном df_authors:", len(df_authors))
print("Уникальных авторов после агрегации:", len(df_authors_agg))
display(df_authors_agg.head())

Строк в исходном df_authors: 1650
Уникальных авторов после агрегации: 1170

,author_URL,birthDate,birthYear,pseudonyms,spouses
0,http://www.wikidata.org/entity/Q1006918,1922-10-11 00:00:00+00:00,1922.0,[],[]
1,http://www.wikidata.org/entity/Q102289,1895-07-12 00:00:00+00:00,1895.0,[Bucky Fuller],[Anne Hewlett]
2,http://www.wikidata.org/entity/Q10278389,1948-11-15 00:00:00+00:00,1948.0,[],[]
3,http://www.wikidata.org/entity/Q1029714,1946-04-18 00:00:00+00:00,1946.0,[],[]
4,http://www.wikidata.org/entity/Q103707994,NaT,NaN,[Will Worthington],[]

In [57]:
# Шаг 4C. Объединяем книги и авторов
df_books_enriched = df_books_unique.merge(
    df_authors_agg,
    on="author_URL",
    how="left",
    validate="m:1"
)

print("Размер объединённой таблицы:", df_books_enriched.shape)
display(df_books_enriched.head())

Размер объединённой таблицы: (3365, 13)

,book_URL,book,author_URL,author_name,genre,pubDate,publisher,pubYear,decade,birthDate,birthYear,pseudonyms,spouses
0,http://www.wikidata.org/entity/Q603705,...Яко помниши его,http://www.wikidata.org/entity/Q34981,Айзек Азимов,научная фантастика,1974-05-01 00:00:00+00:00,NaN,1974,1970,1920-01-02 00:00:00+00:00,1920.0,[Paul French],"[Gertrude Asimov, Джанет Азимова]"
1,http://www.wikidata.org/entity/Q427110,Пересадочная станция,http://www.wikidata.org/entity/Q294625,Клиффорд Дональд Саймак,научная фантастика,1963-06-01 00:00:00+00:00,Doubleday,1963,1960,1904-08-03 00:00:00+00:00,1904.0,[],[Kay Kuchenberg Simak]
2,http://www.wikidata.org/entity/Q1114499,Пасынки Вселенной,http://www.wikidata.org/entity/Q123078,Роберт Хайнлайн,научная фантастика,1963-01-01 00:00:00+00:00,Victor Gollancz,1963,1960,1907-07-07 00:00:00+00:00,1907.0,"[Anson MacDonald, Caleb Saunders, John Riversi...",[Virginia Heinlein]
3,http://www.wikidata.org/entity/Q617357,Убик,http://www.wikidata.org/entity/Q171091,Филип Дик,научная фантастика,1969-01-01 00:00:00+00:00,Doubleday,1969,1960,1928-12-16 00:00:00+00:00,1928.0,"[Jack Dowland, Richard Phillipps]","[Anne R. Dick, Jeanette Marlin, Kleo Mini, Nan..."
4,http://www.wikidata.org/entity/Q388200,The Bloody Sun,http://www.wikidata.org/entity/Q465179,Мэрион Зиммер Брэдли,научная фантастика,1964-01-01 00:00:00+00:00,Ace Books,1964,1960,1930-06-03 00:00:00+00:00,1930.0,"[Alfrida Riversx, Astara Zimmer, Astra Zimmer,...","[Robert Alden Bradley, Walter Breen]"

In [58]:
# Шаг 4D. Возраст автора на момент публикации
df_books_enriched["age_at_publication"] = (
    df_books_enriched["pubYear"] - df_books_enriched["birthYear"]
)

display(
    df_books_enriched[
        ["book", "author_name", "pubYear", "birthYear", "age_at_publication"]
    ].head()
)

,book,author_name,pubYear,birthYear,age_at_publication
0,...Яко помниши его,Айзек Азимов,1974,1920.0,54.0
1,Пересадочная станция,Клиффорд Дональд Саймак,1963,1904.0,59.0
2,Пасынки Вселенной,Роберт Хайнлайн,1963,1907.0,56.0
3,Убик,Филип Дик,1969,1928.0,41.0
4,The Bloody Sun,Мэрион Зиммер Брэдли,1964,1930.0,34.0

In [59]:
# Шаг 4E. Проверяем подозрительные значения
anomalies = df_books_enriched[
    (df_books_enriched["age_at_publication"] < 10) |
    (df_books_enriched["age_at_publication"] > 110)
][[
    "book_URL", "book", "author_URL", "author_name",
    "pubYear", "birthYear", "age_at_publication"
]]

display(anomalies.head(10))
print("Всего подозрительных записей:", len(anomalies))

,book_URL,book,author_URL,author_name,pubYear,birthYear,age_at_publication
767,http://www.wikidata.org/entity/Q6723749,Machines That Think,http://www.wikidata.org/entity/Q191050,Амброз Гвиннет Бирс,1984,1842.0,142.0
776,http://www.wikidata.org/entity/Q6058171,Into the Sun & Other Stories,http://www.wikidata.org/entity/Q1419656,Robert Duncan Milne,1980,1844.0,136.0
1023,http://www.wikidata.org/entity/Q7752158,The Moon Maiden,http://www.wikidata.org/entity/Q953962,Гаррет Сёвисс,1978,1851.0,127.0
1362,http://www.wikidata.org/entity/Q30880226,Q30880226,http://www.wikidata.org/entity/Q42511,Герберт Уэллс,1980,1866.0,114.0
1471,http://www.wikidata.org/entity/Q30880178,The Time Machine and Other Science Fiction Adv...,http://www.wikidata.org/entity/Q42511,Герберт Уэллс,1980,1866.0,114.0
2774,http://www.wikidata.org/entity/Q5146033,Collected Ghost Stories,http://www.wikidata.org/entity/Q276421,Мэри Уилкинс,1974,1852.0,122.0

Всего подозрительных записей: 6

In [60]:
# ✅ Шаг 4. Что можно рисовать в Задании 3?
# Правило: графики строим только по подвыборке, где поле заполнено

print("🔍 Подготовка выборок для визуализации")
print("=" * 60)

# ─────────────────────────────────────────────────────
# 📦 Создаём явные выборки
# ─────────────────────────────────────────────────────
# Полная выборка — для статистики по книгам (уникальные, без дублей)
df_all_books = df_books_unique.copy()

# Подвыборка: только строки, где издатель известен
df_books_with_publisher = df_books_unique[
    df_books_unique["publisher"].notna()
].copy()

# Подвыборка: только строки, где известен год публикации
df_books_with_year = df_books_unique[
    df_books_unique["pubYear"].notna()
].copy()

print(f"📚 Книг всего (уникальных): {len(df_all_books)}")
print(f"🏢 Книг с известным издателем: {len(df_books_with_publisher)} "
      f"({len(df_books_with_publisher)/len(df_all_books)*100:.1f}%)")
print(f"📅 Книг с известным годом публикации: {len(df_books_with_year)} "
      f"({len(df_books_with_year)/len(df_all_books)*100:.1f}%)")

# ─────────────────────────────────────────────────────
# 📊 1. Топ-10 издателей (график: horizontal bar chart)
#    Рисуем ТОЛЬКО по подвыборке, где publisher известен
# ─────────────────────────────────────────────────────
print("\n📊 1. Топ-10 издателей (для графика)")
print("-" * 40)

if "publisher" in df_books_with_publisher.columns and len(df_books_with_publisher) > 0:
    top_publishers = df_books_with_publisher["publisher"].value_counts().head(10)
    display(top_publishers)
    print(f"\n💡 Можно рисовать: горизонтальная столбчатая диаграмма (10 издательств)")
    print(f"💡 Подпись оси Y: 'Количество книг (N={len(df_books_with_publisher)})'")
else:
    print("⚠️ Нет данных для графика по издателям")

# ─────────────────────────────────────────────────────
# 📊 2. Топ-10 авторов (график: bar chart или dot plot)
#    Рисуем по df_all_books, т.к. author_name есть у всех книг
# ─────────────────────────────────────────────────────
print("\n📊 2. Топ-10 самых публикуемых авторов (для графика)")
print("-" * 40)

if "author_name" in df_all_books.columns and df_all_books["author_name"].notna().any():
    top_authors = df_all_books["author_name"].value_counts().head(10)
    display(top_authors)
    print(f"\n💡 Можно рисовать: вертикальная столбчатая диаграмма или dot plot")
    print(f"💡 Подпись: 'Книг на автора (всего уникальных авторов: {df_all_books['author_name'].nunique()})'")
else:
    print("⚠️ Нет данных для графика по авторам")

# ─────────────────────────────────────────────────────
# 📊 3. Распределение по десятилетиям (график: line chart или area chart)
#    Рисуем по подвыборке, где pubYear/decade известен
# ─────────────────────────────────────────────────────
print("\n📊 3. Публикации по десятилетиям (для графика)")
print("-" * 40)

if "decade" in df_books_with_year.columns and df_books_with_year["decade"].notna().any():
    decades = df_books_with_year["decade"].value_counts().sort_index()
    display(decades)
    print(f"\n💡 Можно рисовать: линейный график или area chart по десятилетиям")
    print(f"💡 Подпись оси Y: 'Количество книг (N={len(df_books_with_year)})'")
    print(f"📅 Диапазон: {int(df_books_with_year['pubYear'].min())} — {int(df_books_with_year['pubYear'].max())}")
else:
    print("⚠️ Нет данных для графика по десятилетиям")

# ─────────────────────────────────────────────────────
# 🎯 Бонус: что ещё можно нарисовать в Задании 3?
# ─────────────────────────────────────────────────────
print("\n🎯 Бонус: идеи для визуализаций в Задании 3")
print("-" * 40)

ideas = [
    ("Гистограмма age_at_publication", "df_books_enriched['age_at_publication'].dropna().hist()", "Распределение возраста авторов при публикации"),
    ("Жанры по десятилетиям", "df_books_unique.groupby(['decade', 'genre']).size().unstack()", "Как менялась популярность жанров во времени"),
    ("Издательство × жанр", "df_books_with_publisher.groupby(['publisher', 'genre']).size().unstack().fillna(0)", "Какие издательства специализируются на каких жанрах"),
    ("Возраст автора × жанр", "df_books_enriched.groupby('genre')['age_at_publication'].median().sort_values()", "В каком возрасте чаще пишут в каждом жанре"),
]

for i, (title, code_hint, description) in enumerate(ideas, 1):
    print(f"{i}. {title}")
    print(f"   🔹 {description}")
    print(f"   🔹 Пример кода: {code_hint}\n")

print("=" * 60)
print("✅ Теперь вы знаете, какие графики уместны и по какой выборке их строить")

🔍 Подготовка выборок для визуализации
============================================================
📚 Книг всего (уникальных): 3365
🏢 Книг с известным издателем: 1094 (32.5%)
📅 Книг с известным годом публикации: 3365 (100.0%)

📊 1. Топ-10 издателей (для графика)
----------------------------------------

publisher
Ace Books              113
DAW Books               90
Doubleday               83
Ballantine Books        71
Del Rey Books           63
Arkham House            52
Berkley Books           33
Bantam Books            29
G. P. Putnam's Sons     29
Faber and Faber         23
Name: count, dtype: int64

💡 Можно рисовать: горизонтальная столбчатая диаграмма (10 издательств)
💡 Подпись оси Y: 'Количество книг (N=1094)'

📊 2. Топ-10 самых публикуемых авторов (для графика)
----------------------------------------

author_name
Роберт Силверберг      100
Лин Картер              74
Айзек Азимов            73
Джеймс Блиш             55
Джордж Р. Р. Мартин     52
Майкл Муркок            44
Филип Дик               44
Филип Хосе Фармер       43
Роджер Желязны          42
Артур Чарльз Кларк      41
Name: count, dtype: int64

💡 Можно рисовать: вертикальная столбчатая диаграмма или dot plot
💡 Подпись: 'Книг на автора (всего уникальных авторов: 677)'

📊 3. Публикации по десятилетиям (для графика)
----------------------------------------

decade
1960     761
1970    1401
1980    1203
Name: count, dtype: int64

💡 Можно рисовать: линейный график или area chart по десятилетиям
💡 Подпись оси Y: 'Количество книг (N=3365)'
📅 Диапазон: 1960 — 1985

🎯 Бонус: идеи для визуализаций в Задании 3
----------------------------------------
1. Гистограмма age_at_publication
   🔹 Распределение возраста авторов при публикации
   🔹 Пример кода: df_books_enriched['age_at_publication'].dropna().hist()

2. Жанры по десятилетиям
   🔹 Как менялась популярность жанров во времени
   🔹 Пример кода: df_books_unique.groupby(['decade', 'genre']).size().unstack()

3. Издательство × жанр
   🔹 Какие издательства специализируются на каких жанрах
   🔹 Пример кода: df_books_with_publisher.groupby(['publisher', 'genre']).size().unstack().fillna(0)

4. Возраст автора × жанр
   🔹 В каком возрасте чаще пишут в каждом жанре
   🔹 Пример кода: df_books_enriched.groupby('genre')['age_at_publication'].median().sort_values()

============================================================
✅ Теперь вы знаете, какие графики уместны и по какой выборке их строить

## 📝 Summary

**Что мы сделали в этом ноутбуке (Week 2):**

- ✅ Клонировали репозиторий GitHub в Colab
- ✅ Прочитали 2 CSV-файла из `data/examples/`
- ✅ Удалили URL Wikidata и переименовали столбцы (`*Label → короткие имена`)
- ✅ Проверили структуру данных (размер, столбцы, первые строки)
- ✅ Выполнили быструю валидацию:
  - количество уникальных фильмов, стран, жанров
  - диапазоны значений
  - топ стран и жанров по числу записей
  - типы оценок и результатов

Теперь у нас есть **аккуратные, проверенные таблицы**, с которыми удобно работать дальше.

В отдельном ноутбуке для следующей недели мы будем использовать **те же данные** для:
- более сложного анализа (группировки, фильтрация),
- и построения визуализаций (графики и диаграммы). 🎨